### ISSUE TITLE
SparseCategoricalFocalLoss with class_weight ?

### ISSUE THREAD

**Issue by samuelgjabel** [artemmavrin/focal-loss#10]
Hm..maybe this is weird question. 

But can be used  SparseCategoricalFocalLoss with defining class_weight (for example in model.fit fn) together? Or its bad idea?

Thanks for answer.   :)

**Comment by artemmavrin** [comment]
I think it could be a good idea to try if you have a good reason to weight your classes, but I haven't tried it myself.
