### ISSUE TITLE
No matching distribution found for tensorflow>=2.2 (from focal-loss==0.0.8)

### ISSUE THREAD

**Issue by SightVanish** [artemmavrin/focal-loss#18]
my tensorflow=2.5

**Comment by artemmavrin** [comment]
Hi, can you provide more information about what error you're encountering?

**Comment by SightVanish** [comment]
when I tried to install focal loss via pip, it failed and reported ‘No matching distribution found for tensorflow>=2.2 ‘.
Actually I am using MacBook with apple silicon. There may be something wrong with apple tensorflow. Focal loss is fine with intel machine.
