### ISSUE TITLE
TypeError: sparse_categorical_focal_loss() missing 2 required positional arguments: 'y_true' and 'y_pred'

### ISSUE THREAD

**Issue by mehran66** [artemmavrin/focal-loss#22]
The sparse_categorical_focal_loss needs to have  'y_true' and 'y_pred' identified as inputs.:

model.compile(loss = sparse_categorical_focal_loss(gamma=2, from_logits=False), optimizer=optim, metrics=metrics)

TypeError: sparse_categorical_focal_loss() missing 2 required positional arguments: 'y_true' and 'y_pred'

**Comment by artemmavrin** [comment]
Please try [`SparseCategoricalFocalLoss`](https://focal-loss.readthedocs.io/en/latest/generated/focal_loss.SparseCategoricalFocalLoss.html#focal_loss.SparseCategoricalFocalLoss) instead:
```python
model.compile(loss=SparseCategoricalFocalLoss(gamma=2, from_logits=False)
```

**Comment by mehran66** [comment]
worked, thanks!
