### ISSUE TITLE
SparseCategoricalFocalLoss with RNN

### ISSUE THREAD

**Issue by Abhipray** [artemmavrin/focal-loss#5]
Looks like there's a bug with how sparse categorical focal loss is calculated for sequence model outputs. Here's a colab demonstrating: https://colab.research.google.com/drive/1U1fyl7G1zXRTCS_ZVGMnL3AOKJNX1vZT?usp=sharing

**Comment by artemmavrin** [comment]
Thanks for catching this! Hopefully it's fixed 😄
