### ISSUE TITLE
this is only for tensorflow 2.2 ?

### ISSUE THREAD

**Issue by ramdhan1989** [artemmavrin/focal-loss#7]
is this only used for tensorflow 2.2 ?

**Comment by artemmavrin** [comment]
TensorFlow 2.2 or later. The loss classes use the `tf.keras.utils.register_keras_serializable` decorator, which was introduced in TensorFlow 2.1, and fixed for usage with custom loss functions in TensorFlow 2.2. There might be other version-dependent issues, but that's the biggest one off the top of my head.

**Comment by NgTuong** [comment]
Use to focal loss tf < 2.0, you should comment line https://github.com/artemmavrin/focal-loss/blob/master/src/focal_loss/_binary_focal_loss.py#L269.

**Comment by aditya-iitm** [comment]
> Thank for @artemmavrin, you implemented focal loss + smoothing label
> @artemmavrin , Use to focal loss tf < 2.0, you should comment line https://github.com/artemmavrin/focal-loss/blob/master/src/focal_loss/_binary_focal_loss.py#L269.

I tried running the provided example after doing this in sparse_categorical_focal_loss. I'm getting a `ValueError: batch_dims = 1 must be less than rank(indices) = 1`
